-- AlterTable
ALTER TABLE "Material" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "amount" SET DATA TYPE VARCHAR(10);

-- AlterTable
ALTER TABLE "Recipe" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "Unit" ALTER COLUMN "name" SET DATA TYPE VARCHAR(10);
